/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = new Collection({
    "createRule": null,
    "deleteRule": null,
    "fields": [
      {
        "autogeneratePattern": "[a-z0-9]{15}",
        "help": "",
        "hidden": false,
        "id": "text3208210256",
        "max": 15,
        "min": 15,
        "name": "id",
        "pattern": "^[a-z0-9]+$",
        "presentable": false,
        "primaryKey": true,
        "required": true,
        "system": true,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text724990059",
        "max": 0,
        "min": 0,
        "name": "title",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text3060563083",
        "max": 0,
        "min": 0,
        "name": "shortdescription",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "convertURLs": false,
        "help": "",
        "hidden": false,
        "id": "editor1843675174",
        "maxSize": 0,
        "name": "description",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "editor"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text3182418120",
        "max": 0,
        "min": 0,
        "name": "author",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text3654734809",
        "max": 0,
        "min": 0,
        "name": "penciller",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text2203071480",
        "max": 0,
        "min": 0,
        "name": "genre",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "help": "",
        "hidden": false,
        "id": "text1602912115",
        "max": 0,
        "min": 0,
        "name": "source",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "help": "",
        "hidden": false,
        "id": "select2063623452",
        "maxSelect": 0,
        "name": "status",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "select",
        "values": [
          "Ongoing",
          "Completed",
          "Hiatus",
          "Dropped"
        ]
      },
      {
        "help": "",
        "hidden": false,
        "id": "file2366146245",
        "maxSelect": 0,
        "maxSize": 0,
        "mimeTypes": [
          "image/jpeg",
          "image/jxl",
          "image/jp2",
          "image/jpx",
          "image/vnd.mozilla.apng",
          "image/jpm",
          "image/jxs",
          "image/webp",
          "image/x-xpixmap",
          "image/vnd.adobe.photoshop",
          "image/png",
          "image/gif",
          "image/x-icon",
          "image/bmp",
          "image/tiff",
          "image/avif",
          "image/heic",
          "image/heic-sequence",
          "image/heif",
          "image/heif-sequence",
          "image/vnd.djvu",
          "image/bpg",
          "image/x-icns",
          "image/vnd.dwg",
          "image/vnd.radiance",
          "image/x-xcf",
          "image/x-gimp-pat",
          "image/x-gimp-gbr",
          "image/jxr",
          "image/svg+xml",
          "image/x-portable-bitmap",
          "image/x-portable-graymap",
          "image/x-portable-pixmap"
        ],
        "name": "cover",
        "presentable": false,
        "protected": false,
        "required": false,
        "system": false,
        "thumbs": null,
        "type": "file"
      },
      {
        "hidden": false,
        "id": "autodate2990389176",
        "name": "created",
        "onCreate": true,
        "onUpdate": false,
        "presentable": false,
        "system": false,
        "type": "autodate"
      },
      {
        "hidden": false,
        "id": "autodate3332085495",
        "name": "updated",
        "onCreate": true,
        "onUpdate": true,
        "presentable": false,
        "system": false,
        "type": "autodate"
      }
    ],
    "id": "pbc_440763926",
    "indexes": [],
    "listRule": null,
    "name": "comics",
    "system": false,
    "type": "base",
    "updateRule": null,
    "viewRule": null
  });

  return app.save(collection);
}, (app) => {
  const collection = app.findCollectionByNameOrId("pbc_440763926");

  return app.delete(collection);
})
